# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Linting with web-ext"
        
      # Uses moz web-ext for linting
      - name: web-ext lint
        # You may pin to the exact commit or the version.
        # uses: freaktechnik/web-ext-lint@b4b8253399fc8e173a48f182af8f9fbbb86ae98e
        uses: freaktechnik/web-ext-lint@v1
        with:
          # Root folder of the extension that contains the manifest.json
          extension-root: extension # optional, default is .
          # When enabled, the description of all linter messages are also printed
          verbose: true # optional
      

